import { config } from 'dotenv'

config({ path: '.env' })

export const {
    PORT, NODE_ENV, BACKEND_URL, FRONTEND_URL,
    AWS_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY,
    S3_BUCKET_NAME,
    USER_TABLE_NAME, CHAT_TABLE_NAME, DOCUMENT_TABLE_NAME,
    JWT_SECRET, JWT_EXPIRES_IN, REFRESH_TOKEN_SECRET,
    EMBEDDING_MODELID, AUTHROPIC_VERSION, MAX_TOKEN, ROLE, GENARATE_MODELID,
    TEMPERATURE, TOP_P, TOP_K,
    PINECONE_API_KEY, PINECONE_INDEX_NAME, PINECONE_ENVIRONMENT,
    // Azure AI Foundry
    AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_API_KEY, AZURE_OPENAI_API_VERSION,
    AZURE_LLM_DEPLOYMENT_NAME, AZURE_EMBEDDING_DEPLOYMENT_NAME
} = process.env