import { config } from 'dotenv'

config({ path: '.env' })

export const {
    PORT, NODE_ENV, BACKEND_URL,FRONTEND_URL,
    AWS_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY,
    S3_BUCKET_NAME, CLOUDFRONT_URL,
    USER_TABLE_NAME, CHAT_TABLE_NAME,
    JWT_SECRET, JWT_EXPIRES_IN, REFRESH_TOKEN_SECRET,
    EMBEDDING_MODELID, AUTHROPIC_VERSION, MAX_TOKEN, ROLE, GENARATE_MODELID,
    TEMPERATURE, TOP_P, TOP_K,
    DB_USER, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME, VECTOR_TABLE
} = process.env